/**
 * ReminderService — Calendar, Email & Browser notifications
 * No backend required. ICS + mailto + Notification API.
 */

export function generateICS(event) {
  const fmt = d =>
    d
      .toISOString()
      .replace(/[-:]/g, '')
      .replace(/\.\d{3}/, '');
  const uid = `stargaze-${Date.now()}-${Math.random().toString(36).slice(2)}@stargaze.app`;
  const esc = (s = '') => s.replace(/\n/g, '\\n').replace(/,/g, '\\,').replace(/;/g, '\\;');
  const reminder = event.reminderMinutes || 60;

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//StarGaze//Planner//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `UID:${uid}`,
    `DTSTAMP:${fmt(new Date())}`,
    `DTSTART:${fmt(event.startDate)}`,
    `DTEND:${fmt(event.endDate)}`,
    `SUMMARY:${event.title || 'Stargazing Night'}`,
    `DESCRIPTION:${esc(event.description)}`,
    `LOCATION:${event.location || ''}`,
    'BEGIN:VALARM',
    `TRIGGER:-PT${reminder}M`,
    'ACTION:DISPLAY',
    `DESCRIPTION:${event.title} starts soon!`,
    'END:VALARM',
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n');
}

export function downloadICS(ics, filename = 'stargazing-reminder.ics') {
  const blob = new Blob([ics], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = Object.assign(document.createElement('a'), { href: url, download: filename, style: 'display:none' });
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 100);
}

export function createStargazingReminder(night, locationName) {
  const sunset = new Date(night.sunset);
  const sunrise = new Date(night.sunrise);
  const startDate = new Date(sunset.getTime() + 30 * 60000);
  const timeFmt = { hour: '2-digit', minute: '2-digit' };
  const bestTime = night.bestViewingTime
    ? new Date(night.bestViewingTime).toLocaleTimeString('en-US', timeFmt)
    : 'after sunset';

  const desc = [
    `⭐ Score: ${night.score}/100 (${night.rating})`,
    `${night.moonPhaseIcon} Moon: ${night.moonPhaseName}`,
    `☁️ Cloud: ${night.avgCloudCover}%  💧 Humidity: ${night.avgHumidity}%`,
    `👁️ Visibility: ${(night.avgVisibility / 1000).toFixed(1)}km`,
    `🌡️ Temp: ${night.tempMin}°–${night.tempMax}°C`,
    `🕐 Best viewing: ${bestTime}`,
    `🌅 Sunset: ${sunset.toLocaleTimeString('en-US', timeFmt)}`,
    `🌄 Sunrise: ${sunrise.toLocaleTimeString('en-US', timeFmt)}`,
    `📍 ${locationName}`,
    `\nGenerated by StarGaze`,
  ].join('\n');

  const ics = generateICS({
    title: `🔭 Stargazing — ${night.rating} (${night.score}/100)`,
    description: desc,
    startDate,
    endDate: sunrise,
    location: locationName,
    reminderMinutes: 60,
  });
  downloadICS(ics, `stargazing-${night.date.replace(/-/g, '')}.ics`);
}

export function sendEmailReminder(email, night, locationName) {
  const date = new Date(night.date).toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });
  const bestTime = night.bestViewingTime
    ? new Date(night.bestViewingTime).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
    : 'after sunset';

  const subject = encodeURIComponent(`🔭 Stargazing Reminder: ${night.rating} night on ${date}`);
  const body = encodeURIComponent(
    `Hi! Here's your stargazing reminder:\n\n` +
      `📅 ${date}\n📍 ${locationName}\n⭐ Score: ${night.score}/100 (${night.rating})\n` +
      `${night.moonPhaseIcon} Moon: ${night.moonPhaseName}\n☁️ Cloud: ${night.avgCloudCover}%\n` +
      `🕐 Best time: ${bestTime}\n\nHappy stargazing! 🌌\n— StarGaze`,
  );
  window.open(`mailto:${email}?subject=${subject}&body=${body}`, '_self');
}

export async function requestNotificationPermission() {
  if (!('Notification' in window)) return false;
  if (Notification.permission === 'granted') return true;
  if (Notification.permission === 'denied') return false;
  try {
    return (await Notification.requestPermission()) === 'granted';
  } catch (e) {
    console.warn('Notification.requestPermission failed:', e);
    return false;
  }
}

export function showNotification(title, options = {}) {
  if (!('Notification' in window) || Notification.permission !== 'granted') return null;
  if (!navigator.serviceWorker) return null;
  navigator.serviceWorker
    .getRegistration()
    .then(function (reg) {
      if (!reg) return;
      reg.showNotification(title, { body: options.body || '', tag: 'stargaze', requireInteraction: true });
    })
    .catch(function (e) {
      console.warn('Notification failed:', e);
    });
  return null;
}
